easy_admin:
   site_name: 'MovieDB'
   design:
      brand_color: '#4a0eed'
  #     menu:
  #       - label: 'Films'
  #         children: ['Personnes', 'Postes']
   entities:
        # List the entity class name you want to manage
        Films:
          class: App\Entity\Movie
        Personnes:
          class: App\Entity\Person
        Castings:
          class: App\Entity\Casting
        Genres:
          class: App\Entity\Genre
        Postes:
          class: App\Entity\Job
          # propriété qui permet de spécifier les colonnes qu'on veut voir dans la liste
          list:
              fields: ['id', 'name', 'department']
          # précise les champs parmi lesquels rechercher des informations. On peut préciser des champs d'autres entités en relation avec celle-ci
          search:
              fields: ['name', 'department.name']
          # permet de préciser la liste des champs visible dans le formulaire de cette entité
          form:
              fields: ['name', 'department']
        Departements:
          class: App\Entity\Department
        Equipes:
          class: App\Entity\Team

